// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkerManager.Infrastructure.EF.Contexts;

#nullable disable

namespace WorkerManager.Infrastructure.EF.Migrations
{
    [DbContext(typeof(WorkerManagerDbContext))]
    [Migration("20231204231948_CompletedByWorkerWithIdAdded")]
    partial class CompletedByWorkerWithIdAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkerManager.Domain.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("WorkerManager.Domain.Entities.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompletedByWorkerWithId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TaskStatus")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WorkerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("WorkerId")
                        .IsUnique();

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("WorkerManager.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WorkerManager.Domain.Entities.Manager", b =>
                {
                    b.HasBaseType("WorkerManager.Domain.Entities.User");

                    b.HasDiscriminator().HasValue("Manager");
                });

            modelBuilder.Entity("WorkerManager.Domain.Entities.Worker", b =>
                {
                    b.HasBaseType("WorkerManager.Domain.Entities.User");

                    b.Property<Guid?>("AssignedTaskId")
                        .HasColumnType("uuid");

                    b.HasDiscriminator().HasValue("Worker");
                });

            modelBuilder.Entity("WorkerManager.Domain.Entities.Task", b =>
                {
                    b.HasOne("WorkerManager.Domain.Entities.Manager", "Manager")
                        .WithMany("Tasks")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkerManager.Domain.Entities.Worker", "Worker")
                        .WithOne("AssignedTask")
                        .HasForeignKey("WorkerManager.Domain.Entities.Task", "WorkerId");

                    b.Navigation("Manager");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("WorkerManager.Domain.Entities.User", b =>
                {
                    b.HasOne("WorkerManager.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WorkerManager.Domain.Entities.Manager", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("WorkerManager.Domain.Entities.Worker", b =>
                {
                    b.Navigation("AssignedTask");
                });
#pragma warning restore 612, 618
        }
    }
}
